# Generated by Django 4.2.4 on 2023-08-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('designation', models.CharField(choices=[('Associate', 'Level 1'), ('Senior Associate', 'Level 2'), ('Manager', 'Manager'), ('Senior Manager', 'Senior Manager'), ('Director', 'Director')], max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companymodel')),
            ],
        ),
    ]
